"""empty message

Revision ID: 5194b58a6173
Revises: dda2435c8d7f
Create Date: 2020-04-03 12:25:45.528337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5194b58a6173'
down_revision = 'dda2435c8d7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Artist_image_link_key', 'Artist', type_='unique')
    op.drop_column('Artist', 'image_link')
    op.drop_column('Artist', 'facebook_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('facebook_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.create_unique_constraint('Artist_image_link_key', 'Artist', ['image_link'])
    # ### end Alembic commands ###
