"""empty message

Revision ID: 7f09dafcb5f7
Revises: 5194b58a6173
Create Date: 2020-04-03 12:26:14.385630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f09dafcb5f7'
down_revision = '5194b58a6173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('facebook_link', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('image_link', sa.String(length=500), nullable=True))
    op.create_unique_constraint(None, 'Artist', ['image_link'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Artist', type_='unique')
    op.drop_column('Artist', 'image_link')
    op.drop_column('Artist', 'facebook_link')
    # ### end Alembic commands ###
