"""empty message

Revision ID: d3cd0ca889e9
Revises: 323a32b9f971
Create Date: 2020-04-04 16:29:50.762923

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd3cd0ca889e9'
down_revision = '323a32b9f971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'seeking_venue',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               nullable=True)
    op.drop_column('Venue', 'upcoming_shows')
    op.drop_column('Venue', 'past_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('past_shows', postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('upcoming_shows', postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())), autoincrement=False, nullable=True))
    op.alter_column('Artist', 'seeking_venue',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
