"""empty message

Revision ID: e661da99a187
Revises: d497038bc7bb
Create Date: 2020-04-02 21:09:46.068813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e661da99a187'
down_revision = 'd497038bc7bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('Show_artist_image_link_fkey', 'Show', type_='foreignkey')
    op.drop_constraint('Show_artist_name_fkey', 'Show', type_='foreignkey')
    op.drop_constraint('Show_venue_name_fkey', 'Show', type_='foreignkey')
    op.drop_column('Show', 'start_time')
    op.drop_column('Show', 'artist_name')
    op.drop_column('Show', 'show_id')
    op.drop_column('Show', 'venue_name')
    op.drop_column('Show', 'artist_image_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('artist_image_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Show', sa.Column('venue_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Show', sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('Show', sa.Column('artist_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Show', sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_foreign_key('Show_venue_name_fkey', 'Show', 'Venue', ['venue_name'], ['name'])
    op.create_foreign_key('Show_artist_name_fkey', 'Show', 'Artist', ['artist_name'], ['name'])
    op.create_foreign_key('Show_artist_image_link_fkey', 'Show', 'Artist', ['artist_image_link'], ['image_link'])
    op.drop_column('Show', 'id')
    # ### end Alembic commands ###
